config/routes.rb
Rails.application.routes.draw do
  resources :vistors do
  	collection do
      get :signout_vistor
      get :search_visitor
      get :search_by_user_type
      get :generate_reports
      get :search_by_date
      post :calender_search_record
    end
  end
  get 'welcome/index'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/vistor.rb
class Vistor < ApplicationRecord
	validates_presence_of :username
	validates_presence_of :arrival_date
	validates_presence_of :arrival_time

	VISITOR_TYPE = ["Vistor", "Meeting", "Interview", "Friend/Family Visit"]
	HOST = ["CEO", "CTO", "Designer", "Project Manager"]
	def self.to_csv
    CSV.generate do |csv|
      csv << ["id", "location_name", "signed_in_time_utc", "signed_in_time_local", "signed_out_time_utc",
      	"signed_out_time_local", "your_full_name", "nda_pdf_url", "photo_url", "private_notes","vistor_type" ,"here_for","host"
      ]
      all.each do |vistor|
        csv << [vistor.id, "Said Hq", Vistor.get_arrival_time_local_time(vistor.arrival_time, vistor.arrival_date),
                Vistor.get_arrival_time_utc_time(vistor.arrival_time, vistor.arrival_date),  
                 Vistor.get_utc_time(vistor.checkout_time), Vistor.get_local_time(vistor.checkout_time), 
                 vistor.username, "", "", vistor.note, vistor.visitor_type, vistor.here_for, vistor.host]
      end
    end
  end

  def self.get_local_time(checkout)
    checkout.present? ? checkout.localtime.strftime("%m/%d/%Y %I:%M %p") : "Signed In Now"
  end

  def self.get_utc_time(checkout)
    checkout.present? ? checkout.utc.strftime("%m/%d/%Y %I:%M %p") : "Signed In Now"
  end

  def self.get_arrival_time_local_time(time, date)
    d = Date.new(date.year, date.month, date.day)
    t = time
    dt = DateTime.new(d.year, d.month, d.day, t.hour, t.min, t.sec, t.zone)
    dt.present? ?  dt.localtime.strftime("%m/%d/%Y %I:%M %p"): ""
  end

  def self.get_arrival_time_utc_time(time, date)
    d = Date.new(date.year, date.month, date.day)
    t = time
    dt = DateTime.new(d.year, d.month, d.day, t.hour, t.min, t.sec, t.zone)
    dt.present? ?  dt.utc.strftime("%m/%d/%Y %I:%M %p"): ""
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   protect_from_forgery prepend: true

end

app/controllers/vistors_controller.rb
class VistorsController < ApplicationController
  before_action :set_vistor, only: [:show, :edit, :update, :destroy]

  def index
    @today = Time.now
    @yesterday = Time.now - 1.day
    @tomorrow = Time.now + 1.day
    @vistors = Vistor.where("created_at >= ?",Time.now.beginning_of_day)
  end

  def show
  end

  def new
    @vistor = Vistor.new
  end

  def edit
  end

 
  def create
    @vistor = Vistor.new(vistor_params)

    respond_to do |format|
      if @vistor.save
        format.html { redirect_to vistors_path, notice: 'Vistor was successfully Checked In' }
        format.json { render :show, status: :created, location: @vistor }
      else
        format.html { render :new }
        format.json { render json: @vistor.errors, status: :unprocessable_entity }
      end
    end
  end
 
  def update
    respond_to do |format|
      if @vistor.update(vistor_params)
        format.html { redirect_to @vistor, notice: 'Vistor was successfully Checked In' }
        format.json { render :show, status: :ok, location: @vistor }
      else
        format.html { render :edit }
        format.json { render json: @vistor.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @vistor.destroy
    respond_to do |format|
      format.html { redirect_to vistors_url, notice: 'Vistor was successfully Checked Out.' }
      format.json { head :no_content }
    end
  end

  def signout_vistor
    vistor = Vistor.find_by_id(params[:vistor_id])
    if vistor.present?
      vistor.update_attributes(checkout_time: Time.now)
      redirect_to vistors_url
    else
      redirect_to vistors_url
    end
  end

  def search_visitor
    if params[:search_query].blank? || params[:search_query].nil?
      @vistors = Vistor.all
    else
      @vistors = Vistor.where("username like ?", "%#{params[:search_query]}%")
    end
  end

  def search_by_user_type
    if params[:user_type] == ""
      @vistors = Vistor.all.order(:created_at)
    elsif params[:user_type] == "Currently Signed In"
      @vistors = Vistor.where(checkout_time: nil).order(:created_at)
    elsif params[:user_type] == "Currently Signed Out"
      @vistors = Vistor.where.not(checkout_time: nil).order(:created_at)
    end
  end

  def generate_reports
    @vistor = Vistor.where('created_at BETWEEN ? AND ?', params[:date].to_time.beginning_of_day, params[:date].to_time.end_of_day)
    respond_to do |format|
      format.html
      format.csv { send_data @vistor.to_csv, filename: "vistor_report-#{Time.zone.today}.csv" }
    end
  end

  def search_by_date
    @today = params[:search_by_date].to_date
    @yesterday = @today - 1.day
    @tomorrow = @today + 1.day
    @vistors = Vistor.where('created_at BETWEEN ? AND ?', params[:search_by_date].to_time.beginning_of_day, params[:search_by_date].to_time.end_of_day)
  end


  def calender_search_record
    @today = params[:search][:search_by_date].to_date
    @yesterday = @today - 1.day
    @tomorrow = @today + 1.day
    @vistors = Vistor.where('created_at BETWEEN ? AND ?', params[:search][:search_by_date].to_time.beginning_of_day, params[:search][:search_by_date].to_time.end_of_day)
  end

  private

    def set_vistor
      @vistor = Vistor.find(params[:id])
    end

    def vistor_params
      params.require(:vistor).permit(:username, :contact_number, :email, :visitor_type, :here_for, :host, :note, :arrival_time, :arrival_date)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	layout "landing_page"
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def inline_svg(path)
	  file = File.open("app/assets/images/#{path}", "rb")
	  raw file.read
	end

	def create_hours(parameters)
	  start_time = parameters[:start_time] ? parameters[:start_time] : 0
	  end_time = parameters[:end_time] ? parameters[:end_time] : 24.hours
	  increment = parameters[:increment] ? parameters[:increment] : 15.minutes
	  Array.new(1 + (end_time - start_time)/increment) do |i|
	    (Time.now.midnight + (i*increment) + start_time).strftime("%I:%M %p")
	  end
	end

	def show_errors(object, field_name)
	  if object.errors.any?
	    if !object.errors.messages[field_name].blank?
	      object.errors.messages[field_name].join(", ")
	    end
	  end
	end 

end

app/helpers/vistors_helper.rb
module VistorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Maroc</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag "font-awesome" %>
    <%= stylesheet_link_tag "font-awesome.min" %>
    <%= stylesheet_link_tag "style" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <%= javascript_include_tag 'jquery' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container main-container">
        <div class="row main-row">
            <div class="col-md-2 no-float">
                <header>
                <%= inline_svg("logo.svg") %>
                <div class="tech"><a href= "/welcome/index">Said Tech HQ</a></div>
                </header>

                <header>
                    <nav>
                         <li class="visitor-list-box">
                            <a class="active visitor-list" href="">Visitors</a>
                        </li>

                        <li  class="visitor-list-box">
                            <a class="visitor-list"  href="#">Visitor log</a>
                        </li>
                        
                        <li  class="visitor-list-box">
                            <a class="visitor-list"  href="#">Invites</a>
                        </li>

                        <li  class="visitor-list-box">
                            <a class="visitor-list"  href="#">Analytics</a>
                        </li>

                        <li  class="visitor-list-box">
                            <a class="visitor-list"  href="#">Devices </a>
                        </li>

                        <li  class="visitor-list-box">
                            <a class="visitor-list"  href="#">Settings</a>
                        </li>
                    </nav>
                </header>
            </div>                                                                                                                           

                    
       <!-- Page Content -->
            <div class="col-md-10 float_row no-float">
                <%= yield %>
              </div>
            <!-- Page Content -->
          </div>
        </div>
    </body>
</html>

app/views/layouts/landing_page.html.erb
  <body>

    <header id="first">
        <div class="header-content">
            <div class="inner">
                <h1 class="cursive">Simple, One Page Design</h1>
                <h4>A free landing page theme with video background</h4>
                <hr>
                 <%= link_to 'Check In', new_vistor_path, :class => 'btn btn-primary btn-xl' %> &nbsp; <%= link_to 'Check Out', vistors_path, :class => 'btn btn-primary btn-xl' %>
            </div>
        </div>
    </header>
  </body>


<style type="text/css">

    @import url(https://fonts.googleapis.com/css?family=Questrial);
    @import url(http://fonts.googleapis.com/css?family=Dancing+Script:700);

    html,
    body {
        width: 100%;
        height: 100%;
    }

    body {
        font-family: 'Questrial','Helvetica Neue',Arial,sans-serif;
        background-color: #282828;
        color: #d3d3d3;
        webkit-tap-highlight-color: #222;
    }

    hr {
        max-width: 80px;
        border-width: 3px;
        opacity: 0.09;
        margin-top: 15px;
        margin-bottom: 15px;
    }



    .bg-primary {
        background-color: #333;
    }

    .bg-dark {
        color: #eee;
        background-color: #222;
    }

    .cursive {
        font-family: 'Dancing Script', cursive;
        text-transform: none;
    }

    .text-faded {
        color: rgba(245,245,245,0.7);
    }



    header {
        position: relative;
        min-height: auto;
        text-align: center;
        color: #fff;
        width: 100%;
        background-color: #c9c9c9;
        background-image: url('https://splashbase.s3.amazonaws.com/lifeofpix/regular/Life-of-Pix-free-stock-photos-Slate-Stone-Xeromatic-1440x953.jpg');
        background-position: center;
        -webkit-background-size: cover;
        -moz-background-size: cover;
        background-size: cover;
        -o-background-size: cover;
    }

    header .header-content {
        position: relative;
        width: 100%;
         
        text-align: center;
        z-index: 2;
    }

    header .header-content .inner h1 {
        margin-top: 0;
        margin-bottom: 0;
    }




    @media(min-width:768px) {
        .icon-lg {
            font-size: 80px;
        }
        
        header {
            min-height: 100%;
        }

        header .header-content {
            position: absolute;
            top: 50%;
             
            -webkit-transform: translateY(-50%);
            -ms-transform: translateY(-50%);
            transform: translateY(-50%);
        }

        header .header-content .inner {
            margin-right: auto;
            margin-left: auto;
            max-width: 1000px;
        }

        header .header-content .inner h1 {
            font-size: 53px;
        }

        header .header-content .inner p {
            margin-right: auto;
            margin-left: auto;
            max-width: 80%;
            font-size: 18px;
        }
        
        section {
            min-height: 600px;
           
        }

    }




    .btn.btn-primary {
        background-color: transparent;
        border:1px solid #f0f0f0;
        border-color:#f0f0f0;
        -webkit-transition: all .35s;
        -moz-transition: all .35s;
        transition: all .35s;
        text-decoration: none;
        color: white
    }

    .btn.btn-primary:hover {
        opacity: 0.7;
    }

    .btn {
        border: 0;
        border-radius: 290px;
        font-family: 'Helvetica Neue',Arial,sans-serif;
    }

    .btn-xl {
        padding: 15px 30px;
        font-size: 20px;
    }


</style>

app/views/vistors/_form.html.erb
<div class="col-md-8">
    <h3 class="new-visitor"> 
      <a href= "/welcome/index">
        <i class="fa fa-arrow-circle-left" aria-hidden="true" style="margin-right: 30px; color: black">
        </i>
      </a>New visitor</h3>
</div>

<%= form_with(model: vistor, local: true) do |form| %>
  
  <div class="col-md-8">
      <div class="form-group">
        <label class="label-visitors" for="sel1">VISITOR TYPE</label>
        <%= form.select :visitor_type, options_for_select(Vistor::VISITOR_TYPE, :selected => @vistor.visitor_type),{},{class: "form-control form-class"} %>
      </div>
  </div>

  <div class="clearfix">
    
  </div>

  <div class="col-md-4">
    <div class="form-group">
      <label class="label-visitors" for="usr">ARRIVAL DATE</label>
      <%= form.text_field :arrival_date, 'data-behaviour' => 'datepicker',class: "form-control form-class",:required => true %>
    </div>
   </div>

  <div class="col-md-4">
    <div class="form-group">
      <label class="label-visitors" for="usr">ARRIVAL TIME</label>
      <%= form.select :arrival_time, options_for_select(create_hours(:start_time => 0.hours, :end_time => 23.75.hours)),{},{class: "form-control form-class" ,:required => true} %>
    </div>
  </div>

  <div class="col-md-8">
    <div class="form-group">
      <label class="label-visitors" for="usr">FULL NAME </label><span class="requiredField"></span>
      <%= form.text_field :username, id: :vistor_username, class: "form-control form-class",:required => true %>
      <small class='error'><%= show_errors(@vistor, :username) %></small>
    </div>
  </div>

  <div class="col-md-8">
    <div class="form-group">
      <label class="label-visitors" for="usr">YOU ARE HERE FOR</label>
      <%= form.text_field :here_for, id: :here_for, class: "form-control form-class" %>
    </div>
  </div>

  <div class="col-md-8">
    <div class="form-group">
      <label class="label-visitors" for="usr">YOUR PHONE NUMBER</label>
      <%= form.text_field :contact_number, id: :vistor_contact_number, class: "form-control form-class"  %>
    </div>
  </div>

  <div class="col-md-8">
    <div class="form-group">
      <label class="label-visitors" for="usr">YOUR EMAIL ADDRESS</label>
      <%= form.text_field :email, id: :vistor_email, class: "form-control form-class"  %>
    </div>
  </div>

  <div class="col-md-8">
      <div class="form-group">
      <label class="label-visitors" for="sel1">HOST</label>
        <%= form.select :host, options_for_select(Vistor::HOST, :selected => @vistor.visitor_type),{:include_blank => "Select Host"},{class: "form-control form-class"} %> 
      </div>  
  </div>

  <div class="col-md-8">
    <div class="form-group">
      <label class="label-visitors" for="comment">PRIVATE NOTES</label>
      <%= form.text_area :note, id: :note, class: "form-control form-class", rows: "5"  %>
    </div>
  </div>

  <div class="clearfix"></div>

                                
   <div class="col-md-4">
      <label class="checkbox-inline label-visitors margin-label-visitors"><input type="checkbox" value="">SEND HOST NOTIFICATION</label>
   </div>

  <div class="clearfix"></div>


   <div class="col-md-8 btn-visitor"">
      <%= form.submit "Sign in", :class => 'btn btn-sign' %>
      <%= form.submit "Sign in and add another", :class => 'btn btn-sign-another' %>
   </div>

<%end%>

app/views/vistors/_vistors_page.html.erb
<div class="row">   
    <div class="col-md-6">
        <h3 class="new-visitor"><%=  @vistors.count %> Vistors</h3>
    </div>

    <div class="col-md-4">
        <div class="form-group">
          <input type="text" class="search-query form-control form-class search-icon" id="search-query" placeholder="&#xF002; Search visitors">
        </div>
    </div>

    <div class="col-md-2 search-visitor">
      <%= link_to 'New Vistor', new_vistor_path, :class => 'btn btn-sign' %>
    </div>  

  </div>

  <div class="row">

    <div class="col-md-6 search_by_date_form">
        <button type="button" class="btn arrow-btn yesterday_record_button"><i class="fa fa-chevron-left" aria-hidden="true"></i></button>
        <%= hidden_field_tag :search_by_yesterday, @yesterday, 'data-behaviour' => 'datepicker'%>
        <%= text_field_tag :search_by_calender, @today.strftime('%a, %d %b %Y'), class: "btn arrow-btn", 'data-behaviour' => 'datepicker'%>
        <button type="button" class="btn arrow-btn tomorrow_record_button"><i class="fa fa-chevron-right" aria-hidden="true"></i></button>
        <%= hidden_field_tag :search_by_tomorrow, @tomorrow, 'data-behaviour' => 'datepicker'%>
    </div>
    
    <div class="col-md-4">
      <%= select_tag('search_by_user_type', options_for_select(["Currently Signed In", "Currently Signed Out"]),prompt: "All Visitors", class: 'form-control search_by_user_type', id: 'search_by_user_type') %>
    </div>
    
    <div class="col-md-1">
      <%= link_to 'Export', generate_reports_vistors_path(format: :csv, date: @today), :class => 'btn btn-sign' %>
    </div>
  
  </div>

<br>
<table class="table">
  <thead>
    <tr>
      <th></th>
      <th class="table_heading">NAME</th>
      <th class="table_heading">EMAIL</th>
      <th class="table_heading">CONTACT NO</th>
      <th class="table_heading">SIGN IN</th>
      <th class="table_heading">SIGN OUT</th>
    </tr>
  </thead>
  <tbody class="vistor_record">
    <%= render :partial => 'vistors_records',collection: @vistors, as: :vistor %>
  </tbody>
</table>
<div class="row">
    <div class="col-md-3">
        <h5 class=""><%=  @vistors.count %> Vistors
          <%= link_to 'Export', generate_reports_vistors_path(format: :csv, date: @today), :class => 'export-link' %>
        </h5> 
    </div>
  </div>

app/views/vistors/_vistors_records.html.erb
<tr>
  <td><label class="checkbox-inline ">
      <p class="circle-par">
        <%= vistor.username[0] %>         
      </p>
    </label>
  </td>
  <td class="table_data"><%= vistor.username %></td>
  <td class="table_data2"><%= vistor.email %></td>
  <td class="table_data2"><%= vistor.contact_number %></td>
  <td class="table_data2"><%= vistor.created_at.localtime.strftime("%I:%M %p") %></td>
  <td class="table_data2">
    <% if vistor.checkout_time.present? %>
        <%= vistor.checkout_time.localtime.strftime("%I:%M %p") %>
      <% else %>
        <%= link_to 'Sign out', signout_vistor_vistors_path(vistor_id: vistor.id) %>
      <% end %></td>
</tr>

app/views/vistors/edit.html.erb
<h1>Editing Vistor</h1>

<%= render 'form', vistor: @vistor %>

<%= link_to 'Show', @vistor %> |
<%= link_to 'Back', vistors_path %>

app/views/vistors/index.html.erb
<div class="vistors_record_list">
  <%= render :partial => 'vistors_page'%>
</div>

  


 

app/views/vistors/new.html.erb
<%= render 'form', vistor: @vistor %>

 

app/views/vistors/search_by_date.js.erb
$(".vistors_record_list").html("<%= escape_javascript render partial: 'vistors_page'  %>"); 

app/views/vistors/search_by_user_type.js.erb
$(".vistor_record").html("<%= escape_javascript render partial: 'vistors_records', collection: @vistors, as: :vistor  %>"); 

app/views/vistors/search_visitor.js.erb
$(".vistor_record").html("<%= escape_javascript render partial: 'vistors_records', collection: @vistors, as: :vistor  %>"); 

app/views/vistors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @vistor.username %>
</p>

<p>
  <strong>Contact number:</strong>
  <%= @vistor.contact_number %>
</p>

<p>
  <strong>Email:</strong>
  <%= @vistor.email %>
</p>

<%= link_to 'Edit', edit_vistor_path(@vistor) %> |
<%= link_to 'Back', vistors_path %>

app/views/welcome/index.html.erb
<!-- <body>
    <div class="container page-div">
        <div class="row">
            <div class="main-page">
                <div class="col-md-4 col-md-offset-1 text">
                    <h1>The easiest way to sign in visitors</h1>
                    <p>Collect guest information, capture their photos and have them sign legal documents—all on the iPad.</p>
                    <%= link_to 'Check In', new_vistor_path, :class => 'btn btn-sign' %>
                    <button type="button" class="btn btn-sign btn-lg">Sign up</button>
                </div>
                
            </div>
        </div>    
    </div>
</body>

 -->